### ISSUE TITLE
screenshot in the readme

### ISSUE THREAD

**Issue by staabm** [akuehnis/redaxo5_addon_mediasort#2]
would be cool to get a visual feeling of what this addon achieves

**Comment by akuehnis** [comment]
Select multiple images
![mediasort_1](https://user-images.githubusercontent.com/7479604/45630226-8d1bba00-ba98-11e8-8f10-b251e13ad500.PNG)

Drag&Drop where they should be
![mediasort_2](https://user-images.githubusercontent.com/7479604/45630227-8d1bba00-ba98-11e8-824f-a735a41188e2.PNG)

**Comment by staabm** [comment]
not sure what this screens show, but at least something like that in the readme would be awesome.

**Comment by akuehnis** [comment]
Added a screenshot to readme. I am sure that can be done better, just not by me :-). Thanks for the comment!

**Comment by staabm** [comment]
thanks
